### PR TITLE
LED: Fix flashing back and forth between previous set color and flash color

### LINKED ISSUE #56: LED does not flash between last set color and given color
Hi mat1jaczyyy,

First and foremost, you're doing a fantastic job.

It seems that flashing is note quite the same with the original firmware.

Originally, flashing is done between the last set color and the given color.

Example:
- set pad to 64 (green)
- set flashing to 5 (red)
- -> expected: LED flashes between green and red
- -> actual: LED flashes between red and black

Original behavior is very helpful and can be used to create alternating patterns depending on last set color (black to red or red to black) along with internal tempo.

As that's what I'm using to develop a sequencer, I've only tested this in programmer mode.

(Besides this issue, I'm wondering if you could implement RGB grid flashing/pulsing too, instead of 0-127 color codes, that would be a huge help! Let me know if I should create another separate issue.)

Thanks for your work.

Cheers,
Adrien.

### PR DESCRIPTION
**Pull request by risseraka**
I went and did what you told me not to, ha ha, I'm not suggesting you merge this, as I understand the memory impact this PR adds, no worries.

It fixes half of the previous behavior: flashing a color with previous set color.
E.g. led is red, send flash sysex to green, it now flashes green/red/green/red.

The other half does not work this way, i.e. flashing a black LED (when previous state was a color).
E.g. led is red, send flash sysex to black, it should flash between black and red.

To fix this, `flash_screen` disabled state could be set to an impossible value, like 64, instead of 0.

### CODE REVIEW

**Comment by risseraka** [comment]
Oh, can't put it on draft mode on this repository.
I'll add a tag in the subject.

**Comment by mat1jaczyyy** [comment]
Honestly, doesn't look that bad. I'd take the memory impact for this one.

> The other half does not work this way, i.e. flashing a black LED (when previous state was a color).
> E.g. led is red, send flash sysex to black, it should flash between black and red.

What, is this seriously what the behavior is on stock?

**Comment by mat1jaczyyy** [comment]
@risseraka implemented black LEDs, please check if the behavior matches stock now

File: src/other/tempo.c [hunk 1]
```diff
@@ -41,8 +41,22 @@ void tempo_tick() {
 	// Draw Flashing LEDs
 	u8 flash_state = (tempo_counter % (tempo_bar >> 2)) < (tempo_bar >> 3);
 	for (u8 i = 1; i < 100; i++) {
-		if (flash_screen[i][0] || flash_screen[i][1] || flash_screen[i][2]) {
-			direct_led(i, flash_screen[i][0] * flash_state, flash_screen[i][1] * flash_state, flash_screen[i][2] * flash_state);
+		if (!(flash_screen[i][0] >> 6 || flash_screen[i][1] >> 6 || flash_screen[i][2] >> 6)) {
+			if (flash_state) {
+				direct_led(
+					i,
+					flash_screen[i][0],
```
Comment (risseraka) [inline src/other/tempo.c:48]: To simplify code and avoid if/else through the loop, could we do something like

```c
u8 *screen[] = flash_state ? flash_screen : led_screen
````

Not sure of the correct syntax.

File: src/led/led.c [hunk 2]
```diff
@@ -80,7 +74,7 @@ void pulse_led(u8 p, u8 v) {
 		}
 	}
 	for (int i = 0; i < 3; i++) {
-		flash_screen[p][i] = 0;
+		flash_screen[p][i] = -1;
```
Comment (risseraka) [inline src/led/led.c:77]: Way to go! 👍 

Thought you couldn't have signed integers as it's an unsigned array, but I guess it just cycles back to the highest value (the C programming me from 15 years ago would frown at me).

File: src/sysex/sysex.c [hunk 3]
```diff
@@ -117,21 +117,21 @@ void handle_sysex(u8 port, u8* d, u16 l) {
 		if (active_port != port || mode >= mode_normal) return;
 
 		for (u8* i = d + 1; i < end; i += 4)
-			fast_led(i[0], i[1], i[2], i[3]);
+			fast_led(i[0] & 0x3F, i[1] & 0x3F, i[2] & 0x3F, i[3] & 0x3F);
```
Comment (risseraka) [inline src/sysex/sysex.c:120]: See, you had to copy that line to all 3 function calls, that's what makes me think that it could factored into one.
(But I don't know how, so, I'll only leave that as a nice to have.)

File: src/led/led.c [hunk 4]
```diff
@@ -40,29 +45,18 @@ void novation_led(u8 p, u8 v) {
...
-	if (!v) {
-		rgb_led(p, 0, 0, 0);
-	} else {
-		u8 palette_using = (mode == mode_performance)? settings.palette_selected : palette_novation;
-
-		for (int i = 0; i < 3; i++) {
-			flash_screen[p][i] = palette_value(palette_using, v, i);
-		}
-	}
+	u8 palette_using = (mode == mode_performance)? settings.palette_selected : palette_novation;
```
Comment (risseraka) [inline src/led/led.c:48]: It even simplified the code, I like that.

File: include/led/led.h [hunk 5]
```diff
@@ -7,7 +7,7 @@
 #include "led/palettes.h"
 #include "flash/settings.h"
 
-u8 flash_screen[100][3], pulse_screen[100][3];
+u8 led_screen[100][3], flash_screen[100][3], pulse_screen[100][3];
```
Comment (risseraka) [inline include/led/led.h:10]: So, all in all, that's a 100 * 3 * 8 = 2,400 bytes (2k) memory overhead, if I count that correctly.

Do you have a way to measure the maximum memory that would get allocated through the entire firmware?

As per https://github.com/dvhdr/launchpad-pro, the LPP has 20K CPU RAM and 128K flash RAM in total, but it's not stated how much we get on a custom firmware.

**Review by risseraka — COMMENTED** [review]
Tested it, works like magic.

A few comments / suggestions, but I wouldn't be able to do the changes myself, so if you don't want to bother with them, just merge.

Big cheer, you're a beast. 🎉

File: src/other/tempo.c (hunk 1 above)
Comment (mat1jaczyyy) [reply src/other/tempo.c:48]: it's a matrix, let's not mess with it, really not worth doing this magic to save a line or so

File: src/led/led.c (hunk 2 above)
Comment (mat1jaczyyy) [reply src/led/led.c:77]: Just sets it to 0xFF

File: src/sysex/sysex.c (hunk 3 above)
Comment (mat1jaczyyy) [reply src/sysex/sysex.c:120]: Again, can do this, but don't wanna mess with it when this is more concise and already works

File: include/led/led.h (hunk 5 above)
Comment (mat1jaczyyy) [reply include/led/led.h:10]: No, 300 bytes; a u8 is an 8-bit unsigned value. Just 100*3=300 bytes

File: src/other/tempo.c (hunk 1 above)
Comment (risseraka) [reply src/other/tempo.c:48]: I was more thinking on the if/else operations multiplied by the number of elements in the loop.
If the performance hit is negligible, then that's cool.

File: include/led/led.h (hunk 5 above)
Comment (risseraka) [reply include/led/led.h:10]: Oops, wow, great, even better than what I had calculated.
Doing some custom lighting sequences could be feasible (something like multi-color flashing), it really opens up possibilities.
Note that it's not intended to go into this performance firmware, don't worry about me blowing your RAM. 😁 
Thanks!

File: src/other/tempo.c (hunk 1 above)
Comment (mat1jaczyyy) [reply src/other/tempo.c:48]: the generated code is negligibly smaller, while likely being slower in a performance critical point...
https://godbolt.org/z/TMjefbqeo

Comment (risseraka) [reply src/other/tempo.c:48]: Well, I would guess that only the 5 last lines would get executed X times in the loop.

```c
screen = state ? foo : bar

for () {
   func(screen, a, b, c)
}
```
vs.

```c
for () {
   if (state) {
     func(foo)
   } else {
     func(bar)
   }
}
```

You're the boss, it's not really my domain of expertise!

Cheers.

File: src/other/tempo.c [hunk 6]
```diff
@@ -41,8 +41,22 @@ void tempo_tick() {
...
+					flash_screen[i][1],
+					flash_screen[i][2]
+				);
+			} else {
```
Comment (risseraka) [inline src/other/tempo.c:52]:
```suggestion
			} else if (flash_screen[i][0] !== led_screen[i][0] || flash_screen[i][1] !== led_screen[i][1] || flash_screen[i][2] !== led_screen[i][2]) {
```


Maybe needed, as if `led_screen`'s color is the same as `flash_screen`'s, it will light the LED for nothing as the color won't change.

WDYT?

Comment (mat1jaczyyy) [reply src/other/tempo.c:52]: nah tbh I don't think this matters too much, anyone that's using flashing probably won't be sending rainbow magic light effects that eat a huge amount of bandwidth
